apiVersion: v1
kind: ConfigMap
metadata:
  name: sp-collector-kafka-config
  namespace: kafka
data:
  config.hocon: |+
    collector {
      interface = "0.0.0.0"
      port = 9090

      streams {
        good = "snowplow-good"
        bad = "snowplow-bad"

        sink {
          brokers = "snowplow-kafka-bootstrap.kafka:9092"
        }
      }
    }