apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: sp-collector-kafka
  name: sp-collector-kafka
  namespace: kafka
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: sp-collector-kafka
status:
  loadBalancer: {}
