# 1 control plane node and 3 workers
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
# the control plane node config
- role: control-plane
  # extraPortMappings:
  # - containerPort: 28083
  #   hostPort: 8083
# the three workers
- role: worker
- role: worker
- role: worker