apiVersion: v1
kind: ConfigMap
metadata:
  name: sp-enricher-kafka-config
  namespace: kafka
data:
  iglu_resolver.json: |+
    {
      "schema": "iglu:com.snowplowanalytics.iglu/resolver-config/jsonschema/1-0-1",
      "data": {
        "cacheSize": 500,
        "repositories": [
          {
            "name": "Iglu Central",
            "priority": 0,
            "vendorPrefixes": [ "com.snowplowanalytics" ],
            "connection": {
              "http": {
                "uri": "http://iglucentral.com"
              }
            }
          }
        ]
      }
    }
  enrich.hocon: |+
    enrich {

      streams {

        in {
          raw = snowplow-good
        }

        out {
          enriched = snowplow-enriched-good
          bad = snowplow-enriched-bad
          pii = snowplow-pii

          partitionKey = user_ipaddress
        }

        sourceSink {
          enabled = kafka

          brokers = "snowplow-kafka-bootstrap.kafka:9092"
          
          # Number of retries to perform before giving up on sending a record
          retries = 1
        }

        buffer {
          byteLimit = 16384
          recordLimit = 0 # Not supported by Kafka; will be ignored
          timeLimit = 1000
        }

        appName = "snowplow-enrich"
      }
    }